# Generated by Django 3.2.4 on 2022-12-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20221215_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='postratings',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
