# Generated by Django 3.2.4 on 2022-12-15 21:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20221215_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrating',
            name='rating',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='postrating',
            unique_together={('user', 'post')},
        ),
    ]
