# Generated by Django 3.2.4 on 2022-12-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20221216_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
